sistemaInit(Prim, Ps, Susc) 
& sistNuevoProc(Prim, Ps, Susc, W, Rep_o1, Prim1, Ps1, Susc1) 
& sistNuevoProc(Prim1, Ps1, Susc1, Z, Rep_o2, Prim2, Ps2, Susc2) 
& sistSuscProceso(Prim2, Ps2, Susc2, W, activate, Rep_o3, Prim3, Ps3, Susc3) 
& sistSuscProceso(Prim3, Ps3, Susc3, Z, suspend, Rep_o4, Prim4, Ps4, Susc4) 
& sistSuscProceso(Prim4, Ps4, Susc4, Z, activate, Rep_o5, Prim5, Ps5, Susc5) 
& sistActivate(Prim5, Ps5, Susc5, Prim6, Ps6, Susc6, Rep_o6) 
& sistSuspend(Ps6, Susc6, Prim7, Ps7, Susc7, Rep_o7)
& sistSuscProceso(Prim7, Ps7, Susc7, Z, kill, Rep_o8, Prim8, Ps8, Susc8) 
& sistKill(Prim8, Ps8, Susc8, Prim9, Ps9, Susc9, Rep_o9)
& dec([Rep_o1, Rep_o2, Rep_o3, Rep_o4, Rep_o5, Rep_o6, Rep_o7, Rep_o8, Rep_o9], msg)
& dec([Prim, Prim1, Prim2, Prim3, Prim4, Prim5, Prim6, Prim7, Prim8, Prim9], pid)
& dec([Ps, Ps1, Ps2, Ps3, Ps4, Ps5, Ps6, Ps7, Ps8, Ps9], ps)
& dec([Susc, Susc1, Susc2, Susc3, Susc4, Susc5, Susc6, Susc7, Susc8, Susc9], suscritos)
& dec([W,Z], pid).